# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: detect.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64\x65tect.proto\x12\x19\x65lectrical_cabinet_detect\"*\n\x0c\x44\x65tectionReq\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"/\n\x11\x44\x65tectionResponse\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t2\x83\x01\n\x19\x45lectrical_Cabinet_Detect\x12\x66\n\tdetection\x12\'.electrical_cabinet_detect.DetectionReq\x1a,.electrical_cabinet_detect.DetectionResponse\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detect_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DETECTIONREQ']._serialized_start=43
  _globals['_DETECTIONREQ']._serialized_end=85
  _globals['_DETECTIONRESPONSE']._serialized_start=87
  _globals['_DETECTIONRESPONSE']._serialized_end=134
  _globals['_ELECTRICAL_CABINET_DETECT']._serialized_start=137
  _globals['_ELECTRICAL_CABINET_DETECT']._serialized_end=268
# @@protoc_insertion_point(module_scope)
