# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import detect_pb2 as detect__pb2


class Electrical_Cabinet_DetectStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.detection = channel.stream_unary(
                '/electrical_cabinet_detect.Electrical_Cabinet_Detect/detection',
                request_serializer=detect__pb2.DetectionReq.SerializeToString,
                response_deserializer=detect__pb2.DetectionResponse.FromString,
                )


class Electrical_Cabinet_DetectServicer(object):
    """Missing associated documentation comment in .proto file."""

    def detection(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Electrical_Cabinet_DetectServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'detection': grpc.stream_unary_rpc_method_handler(
                    servicer.detection,
                    request_deserializer=detect__pb2.DetectionReq.FromString,
                    response_serializer=detect__pb2.DetectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'electrical_cabinet_detect.Electrical_Cabinet_Detect', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Electrical_Cabinet_Detect(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def detection(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/electrical_cabinet_detect.Electrical_Cabinet_Detect/detection',
            detect__pb2.DetectionReq.SerializeToString,
            detect__pb2.DetectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
