# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import hello_pb2 as hello__pb2


class BililiStub(object):
    """Bilili: 服务名
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Hello = channel.unary_unary(
                '/test.Bilili/Hello',
                request_serializer=hello__pb2.HelloReq.SerializeToString,
                response_deserializer=hello__pb2.HelloReply.FromString,
                )
        self.HelloTest = channel.stream_stream(
                '/test.Bilili/HelloTest',
                request_serializer=hello__pb2.HelloTestRequest.SerializeToString,
                response_deserializer=hello__pb2.HelloTestResponse.FromString,
                )
        self.TestClientRecStream = channel.unary_stream(
                '/test.Bilili/TestClientRecStream',
                request_serializer=hello__pb2.TestClientRecStreamRequest.SerializeToString,
                response_deserializer=hello__pb2.TestClientRecStreamResponse.FromString,
                )
        self.TestClientSendStream = channel.stream_unary(
                '/test.Bilili/TestClientSendStream',
                request_serializer=hello__pb2.TestClientSendStreamRequest.SerializeToString,
                response_deserializer=hello__pb2.TestClientSendStreamResponse.FromString,
                )
        self.TestTwoWayStream = channel.stream_stream(
                '/test.Bilili/TestTwoWayStream',
                request_serializer=hello__pb2.TestTwoWayStreamRequest.SerializeToString,
                response_deserializer=hello__pb2.TestTwoWayStreamResponse.FromString,
                )


class BililiServicer(object):
    """Bilili: 服务名
    """

    def Hello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HelloTest(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestClientRecStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestClientSendStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestTwoWayStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BililiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Hello': grpc.unary_unary_rpc_method_handler(
                    servicer.Hello,
                    request_deserializer=hello__pb2.HelloReq.FromString,
                    response_serializer=hello__pb2.HelloReply.SerializeToString,
            ),
            'HelloTest': grpc.stream_stream_rpc_method_handler(
                    servicer.HelloTest,
                    request_deserializer=hello__pb2.HelloTestRequest.FromString,
                    response_serializer=hello__pb2.HelloTestResponse.SerializeToString,
            ),
            'TestClientRecStream': grpc.unary_stream_rpc_method_handler(
                    servicer.TestClientRecStream,
                    request_deserializer=hello__pb2.TestClientRecStreamRequest.FromString,
                    response_serializer=hello__pb2.TestClientRecStreamResponse.SerializeToString,
            ),
            'TestClientSendStream': grpc.stream_unary_rpc_method_handler(
                    servicer.TestClientSendStream,
                    request_deserializer=hello__pb2.TestClientSendStreamRequest.FromString,
                    response_serializer=hello__pb2.TestClientSendStreamResponse.SerializeToString,
            ),
            'TestTwoWayStream': grpc.stream_stream_rpc_method_handler(
                    servicer.TestTwoWayStream,
                    request_deserializer=hello__pb2.TestTwoWayStreamRequest.FromString,
                    response_serializer=hello__pb2.TestTwoWayStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'test.Bilili', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Bilili(object):
    """Bilili: 服务名
    """

    @staticmethod
    def Hello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/test.Bilili/Hello',
            hello__pb2.HelloReq.SerializeToString,
            hello__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HelloTest(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/test.Bilili/HelloTest',
            hello__pb2.HelloTestRequest.SerializeToString,
            hello__pb2.HelloTestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TestClientRecStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/test.Bilili/TestClientRecStream',
            hello__pb2.TestClientRecStreamRequest.SerializeToString,
            hello__pb2.TestClientRecStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TestClientSendStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/test.Bilili/TestClientSendStream',
            hello__pb2.TestClientSendStreamRequest.SerializeToString,
            hello__pb2.TestClientSendStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TestTwoWayStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/test.Bilili/TestTwoWayStream',
            hello__pb2.TestTwoWayStreamRequest.SerializeToString,
            hello__pb2.TestTwoWayStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
