# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhello.proto\x12\x04test\"%\n\x08HelloReq\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\"\x1c\n\nHelloReply\x12\x0e\n\x06result\x18\x01 \x01(\t\";\n\x10HelloTestRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\t\"\x13\n\x11HelloTestResponse\"*\n\x1aTestClientRecStreamRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"-\n\x1bTestClientRecStreamResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"+\n\x1bTestClientSendStreamRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\".\n\x1cTestClientSendStreamResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"\'\n\x17TestTwoWayStreamRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"*\n\x18TestTwoWayStreamResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\x95\x03\n\x06\x42ilili\x12+\n\x05Hello\x12\x0e.test.HelloReq\x1a\x10.test.HelloReply\"\x00\x12\x42\n\tHelloTest\x12\x16.test.HelloTestRequest\x1a\x17.test.HelloTestResponse\"\x00(\x01\x30\x01\x12^\n\x13TestClientRecStream\x12 .test.TestClientRecStreamRequest\x1a!.test.TestClientRecStreamResponse\"\x00\x30\x01\x12\x61\n\x14TestClientSendStream\x12!.test.TestClientSendStreamRequest\x1a\".test.TestClientSendStreamResponse\"\x00(\x01\x12W\n\x10TestTwoWayStream\x12\x1d.test.TestTwoWayStreamRequest\x1a\x1e.test.TestTwoWayStreamResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HELLOREQ']._serialized_start=21
  _globals['_HELLOREQ']._serialized_end=58
  _globals['_HELLOREPLY']._serialized_start=60
  _globals['_HELLOREPLY']._serialized_end=88
  _globals['_HELLOTESTREQUEST']._serialized_start=90
  _globals['_HELLOTESTREQUEST']._serialized_end=149
  _globals['_HELLOTESTRESPONSE']._serialized_start=151
  _globals['_HELLOTESTRESPONSE']._serialized_end=170
  _globals['_TESTCLIENTRECSTREAMREQUEST']._serialized_start=172
  _globals['_TESTCLIENTRECSTREAMREQUEST']._serialized_end=214
  _globals['_TESTCLIENTRECSTREAMRESPONSE']._serialized_start=216
  _globals['_TESTCLIENTRECSTREAMRESPONSE']._serialized_end=261
  _globals['_TESTCLIENTSENDSTREAMREQUEST']._serialized_start=263
  _globals['_TESTCLIENTSENDSTREAMREQUEST']._serialized_end=306
  _globals['_TESTCLIENTSENDSTREAMRESPONSE']._serialized_start=308
  _globals['_TESTCLIENTSENDSTREAMRESPONSE']._serialized_end=354
  _globals['_TESTTWOWAYSTREAMREQUEST']._serialized_start=356
  _globals['_TESTTWOWAYSTREAMREQUEST']._serialized_end=395
  _globals['_TESTTWOWAYSTREAMRESPONSE']._serialized_start=397
  _globals['_TESTTWOWAYSTREAMRESPONSE']._serialized_end=439
  _globals['_BILILI']._serialized_start=442
  _globals['_BILILI']._serialized_end=847
# @@protoc_insertion_point(module_scope)
