# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import arithmetic_pb2 as arithmetic__pb2


class ArithmeticServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.analysis = channel.unary_stream(
                '/ArithmeticService/analysis',
                request_serializer=arithmetic__pb2.TaskAssets.SerializeToString,
                response_deserializer=arithmetic__pb2.TaskAssetResponse.FromString,
                )


class ArithmeticServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def analysis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArithmeticServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'analysis': grpc.unary_stream_rpc_method_handler(
                    servicer.analysis,
                    request_deserializer=arithmetic__pb2.TaskAssets.FromString,
                    response_serializer=arithmetic__pb2.TaskAssetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ArithmeticService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ArithmeticService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def analysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ArithmeticService/analysis',
            arithmetic__pb2.TaskAssets.SerializeToString,
            arithmetic__pb2.TaskAssetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
