# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arithmetic.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61rithmetic.proto\",\n\nTaskAssets\x12\x1e\n\ntask_asset\x18\x01 \x03(\x0b\x32\n.TaskAsset\"L\n\tTaskAsset\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08location\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65vice_name\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\"\xb0\x01\n\x11TaskAssetResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12$\n\rlocation_wrap\x18\x02 \x03(\x0b\x32\r.LocationWrap\x12\x36\n\nattributes\x18\x03 \x03(\x0b\x32\".TaskAssetResponse.AttributesEntry\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"=\n\x0cLocationWrap\x12\x10\n\x08location\x18\x01 \x01(\t\x12\x1b\n\x04type\x18\x02 \x01(\x0e\x32\r.AnalysisType**\n\x0c\x41nalysisType\x12\x0c\n\x08ORIGINAL\x10\x00\x12\x0c\n\x08\x41NALYSIS\x10\x01\x32\x44\n\x11\x41rithmeticService\x12/\n\x08\x61nalysis\x12\x0b.TaskAssets\x1a\x12.TaskAssetResponse\"\x00\x30\x01\x42I\n.com.yunmo.drone.inspection.apirpc.task.serviceB\x0f\x41rithmeticProtoP\x01\xa2\x02\x03RTGb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arithmetic_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n.com.yunmo.drone.inspection.apirpc.task.serviceB\017ArithmeticProtoP\001\242\002\003RTG'
  _TASKASSETRESPONSE_ATTRIBUTESENTRY._options = None
  _TASKASSETRESPONSE_ATTRIBUTESENTRY._serialized_options = b'8\001'
  _globals['_ANALYSISTYPE']._serialized_start=386
  _globals['_ANALYSISTYPE']._serialized_end=428
  _globals['_TASKASSETS']._serialized_start=20
  _globals['_TASKASSETS']._serialized_end=64
  _globals['_TASKASSET']._serialized_start=66
  _globals['_TASKASSET']._serialized_end=142
  _globals['_TASKASSETRESPONSE']._serialized_start=145
  _globals['_TASKASSETRESPONSE']._serialized_end=321
  _globals['_TASKASSETRESPONSE_ATTRIBUTESENTRY']._serialized_start=272
  _globals['_TASKASSETRESPONSE_ATTRIBUTESENTRY']._serialized_end=321
  _globals['_LOCATIONWRAP']._serialized_start=323
  _globals['_LOCATIONWRAP']._serialized_end=384
  _globals['_ARITHMETICSERVICE']._serialized_start=430
  _globals['_ARITHMETICSERVICE']._serialized_end=498
# @@protoc_insertion_point(module_scope)
